#!/usr/bin/env bash
# It displays numbers from 1 to 100 if a list format
# if number is multiple of 3 and 5 displays "FizzBuzz"
# if number is multiple of 3 displays "Fizz"
# if number is multiple of 5 displays "Buzz"

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
