#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 4th iteration displaying "bad luck"
# and for the 8th iteration displaying "good luck"

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
