#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and
# displaying "bad luck from China" after 4th iteration
# and displaying "bad luck from Japan" after 9th iteration
# and displaying "bad luck from Italy" after 17th iteration

i=1
while [ $i -lt 21 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
